#!/bin/bash

function generate_unique_id {
	ID_PREFIX=$1
	[ "" == "${INTERFACE}" ] && INTERFACE=$(ifconfig | grep "^eth" | awk '{print $1}')
	[ "" == "${INTERFACE}" ] && INTERFACE=$(ifconfig | grep "^em" | awk '{print $1}')
	[ "" == "${INTERFACE}" ] && INTERFACE=$(ifconfig | grep "^wlan" | awk '{print $1}')
	if [ "" == "${INTERFACE}" ]; then
		echo "${ID_PREFIX}-xxxxxx"
	else
		MAC=$(ifconfig ${INTERFACE} | grep HWaddr | grep ${INTERFACE} | sed 's/.*HWaddr //g' | sed 's/://g')
		echo "${ID_PREFIX}-${MAC}"
	fi
}

function read_bbb_id {
	ID_PREFIX="bbb"

	# BeagleBone-Black
	#
	EEPROM="/sys/bus/i2c/devices/1-0050/eeprom"
	[ ! -f "${EEPROM}" ] && EEPROM="/sys/bus/i2c/devices/0-0050/eeprom"

	# BeagleBone-Green
	#
	[ ! -f "${EEPROM}" ] && EEPROM="/sys/bus/i2c/devices/0-0050/at24-0/nvmem" && ID_PREFIX="bbg"

	if [ ! -f "${EEPROM}" ]; then
		echo ""
	else
		SERIAL=$(hexdump -e '8/1 "%c"' "${EEPROM}" -s 16 -n 12 2>&1)
		echo "${ID_PREFIX}-${SERIAL}"
	fi
}

function find_unique_id {
	if [ "" != "$(virt-what)" ]; then
		generate_unique_id "vm"
	else
		ID=$(read_bbb_id)
		if [ "" == "${ID}" ]; then
			generate_unique_id "devboard"
		else
			echo ${ID}
		fi
	fi
}

